import Util from '../../utils.js';
import Field from '../field.js';

export default class Alignment extends Field {
  /**
   * This field provides content creators a way to position an element within a container.
   * This should not be used for text alignment as there is a field type specifically for
   * that. Alignment fields are supported in modules. Alignment fields can only be used
   * as style fields.
   * @see {@link https://developers.hubspot.com/en/docs/cms/building-blocks/module-theme-fields#alignment}
   * @param {object} data The JSON data used to generate the field.
   * @param {object} [data.default={}] Object containing "horizontal_align" and
   * "vertical_align".
   * @param {('LEFT'|'RIGHT'|'CENTER')} [data.default.horizontal_align] // @todo 
   * @param {('TOP'|'BOTTOM'|'MIDDLE')} [data.default.vertical_align] // @todo
   * @param {('HORIZONTAL'|'VERTICAL'|'BOTH')} [data.alignment_direction='BOTH'] Determines
   * if only horizontal, only vertical, or both alignment controls should be shown
   * -------------------------------------------------------------------------------------
   * @param {string} [data.help_text] Text that will appear in the editor via tooltip to
   * assist the content creator. Best used for information that is supplementary but not
   * required to use the field.
   * @param {string} [data.id] Unique id for a field. This is generated by HubSpot. When
   * building locally you do not need to specify this id.
   * @param {string} [data.inline_help_text] Help text that will be shown inline below the
   * label of the field (limit 300 chars). Best used for information required to use the
   * field.
   * @param {string} [data.label='Alignment field'] The text the content creator sees
   * describing the field. May contain spaces.
   * @param {boolean} [data.locked=false] Determines if the field is editable in the content
   * editor. If true, the field will not appear in the content editor.
   * @param {string} [data.name='alignment_field'] The variable name you will use to refer
   * to this field's values, and is what the value of the field is stored against. Cannot
   * contain spaces or special characters. If no name is provided, it will default to a lower 
   * snake case value of the label.
   * @param {boolean} [data.required=false] Determines if the field can be left blank in the
   * editor. If true, content will not be allowed to publish without filling out this field.
   * @param {Array} [data.visibility] Determines the display conditions for a field.
   * @param {'half_width'|null} [data.display_width=null] Allows for side by side module
   * fields in content editors, rather than full-width fields, when set to "half_width". The
   * field will appear side-by-side with the next field in the fields.json file, as long as
   * that field is also set to "half_width".
   */
  constructor (data = {}) {
    super(data);
    this.label = data.label || 'Alignment field';
    this.default = data.default || {};
    this.alignment_direction = data.alignment_direction || 'BOTH';

    /**
     * Case-insensitize some property values.
     */
    if (this.alignment_direction) {
      this.alignment_direction = this.alignment_direction.toUpperCase?.(); 
    }
    if (this.default?.horizontal_align) {
      this.default.horizontal_align = this.default.horizontal_align.toUpperCase?.(); 
    }
    if (this.default?.vertical_align) {
      this.default.vertical_align = this.default.vertical_align.toUpperCase?.(); 
    }

    /**
     * @readonly
     * @private
     */
    this.type = 'alignment';

    /**
     * Manually defined names get priority. If no name is set, try to set it to the lower
     * snake case of the label provided. If no label is set, fall back to hardcoded value.
     */
    this.name = data.name || Util.toSnakeCase(this.label) || 'alignment_field';
  }
}
