import Util from '../../utils.js';
import Field from '../field.js';

export default class BackgroundImage extends Field {
  /**
   * This field provides a background image field which has subfields for background
   * position and background size. Background image fields have a .css property that
   * returns CSS based on the field's value. Background Image fields are supported in
   * modules. Background Image fields can only be used as style fields.
   * @see {@link https://developers.hubspot.com/en/docs/cms/building-blocks/module-theme-fields#background-image}
   * @see {@link https://developers.hubspot.com/docs/cms/building-blocks/module-theme-fields-overview#generated-css}
   * @param {object} data The JSON data used to generate the field.
   * @param {object} [data.default={src: '', background_position: 'MIDDLE_CENTER', background_size: 'cover'}]
   * Object containing the image src, background position and background size.
   * @param {string} [data.default.src=''] // @todo
   * @param {('MIDDLE_CENTER'|/* @todo)} [data.default.background_position='MIDDLE_CENTER'] // @todo
   * @param {('cover'|/* @todo)} [data.default.background_size='cover'] // @todo
   * -------------------------------------------------------------------------------------
   * @param {string} [data.help_text] Text that will appear in the editor via tooltip to
   * assist the content creator. Best used for information that is supplementary but not
   * required to use the field.
   * @param {string} [data.id] Unique id for a field. This is generated by HubSpot. When
   * building locally you do not need to specify this id.
   * @param {string} [data.inline_help_text] Help text that will be shown inline below the
   * label of the field (limit 300 chars). Best used for information required to use the
   * field.
   * @param {string} [data.label='Backgroundimage field'] The text the content creator sees
   * describing the field. May contain spaces.
   * @param {boolean} [data.locked=false] Determines if the field is editable in the content
   * editor. If true, the field will not appear in the content editor.
   * @param {string} [data.name='backgroundimage_field'] The variable name you will use to refer
   * to this field's values, and is what the value of the field is stored against. Cannot
   * contain spaces or special characters. If no name is provided, it will default to a lower 
   * snake case value of the label.
   * @param {boolean} [data.required=false] Determines if the field can be left blank in the
   * editor. If true, content will not be allowed to publish without filling out this field.
   * @param {Array} [data.visibility] Determines the display conditions for a field.
   * @param {'half_width'|null} [data.display_width=null] Allows for side by side module
   * fields in content editors, rather than full-width fields, when set to "half_width". The
   * field will appear side-by-side with the next field in the fields.json file, as long as
   * that field is also set to "half_width".
   */
  constructor (data = {}) {
    super(data);
    this.label = data.label || 'Backgroundimage field';
    this.default = data.default || {
      src: '',
      background_position: 'MIDDLE_CENTER',
      background_size: 'cover'
    };

    /**
     * Case-insensitize some property values.
     */
    if (this.alignment_direction) {
      this.alignment_direction = this.alignment_direction.toUpperCase?.(); 
    }
    if (this.default?.background_position) {
      this.default.background_position = this.default.background_position.toUpperCase?.(); 
    }
    if (this.default?.background_size) {
      this.default.background_size = this.default.background_size.toLowerCase?.(); 
    }

    /**
     * @readonly
     * @private
     */
    this.type = 'backgroundimage';

    /**
     * Manually defined names get priority. If no name is set, try to set it to the lower
     * snake case of the label provided. If no label is set, fall back to hardcoded value.
     */
    this.name = data.name || Util.toSnakeCase(this.label) || 'backgroundimage_field';
  }
}
