import Util from '../../utils.js';
import Field from '../field.js';

export default class Gradient extends Field {
  /**
   * This field provides a way for content creators to create and configure gradients. At
   * this time linear gradients support up to 5 color stops. Gradient fields have a .css
   * property that returns CSS based on the field's value. Gradient fields are supported
   * in modules. Gradient fields can only be used as style fields.
   * @see {@link https://developers.hubspot.com/en/docs/cms/building-blocks/module-theme-fields#gradient}
   * @see {@link https://developers.hubspot.com/docs/cms/building-blocks/module-theme-fields-overview#generated-css}
   * @param {object} data The JSON data used to generate the field.
   * @param {object} [data.default={}] Object containing directional settings for a
   * gradient ("side_or_corner") and color stops for the gradient as an array of objects.
   * @param {Array<object>} [data.default.colors] // @todo
   * @param {object} [data.default.colors.color] // @todo
   * @param {object} [data.default.side_or_corner] // @todo
   * @param {('LEFT'|'RIGHT'|'CENTER')/* @todo Not sure if these are right} [data.default.side_or_corner.horizontalSide] // @todo
   * @param {('TOP'|'BOTTOM'|'MIDDLE')/* @todo Not sure if these are right} [data.default.side_or_corner.verticalSide] // @todo
   * -------------------------------------------------------------------------------------
   * @param {string} [data.help_text] Text that will appear in the editor via tooltip to
   * assist the content creator. Best used for information that is supplementary but not
   * required to use the field.
   * @param {string} [data.id] Unique id for a field. This is generated by HubSpot. When
   * building locally you do not need to specify this id.
   * @param {string} [data.inline_help_text] Help text that will be shown inline below the
   * label of the field (limit 300 chars). Best used for information required to use the
   * field.
   * @param {string} [data.label='Gradient field'] The text the content creator sees
   * describing the field. May contain spaces.
   * @param {boolean} [data.locked=false] Determines if the field is editable in the content
   * editor. If true, the field will not appear in the content editor.
   * @param {string} [data.name='gradient_field'] The variable name you will use to refer
   * to this field's values, and is what the value of the field is stored against. Cannot
   * contain spaces or special characters. If no name is provided, it will default to a lower 
   * snake case value of the label.
   * @param {boolean} [data.required=false] Determines if the field can be left blank in the
   * editor. If true, content will not be allowed to publish without filling out this field.
   * @param {Array} [data.visibility] Determines the display conditions for a field.
   * @param {'half_width'|null} [data.display_width=null] Allows for side by side module
   * fields in content editors, rather than full-width fields, when set to "half_width". The
   * field will appear side-by-side with the next field in the fields.json file, as long as
   * that field is also set to "half_width".
   */
  constructor (data = {}) {
    super(data);
    this.label = data.label || 'Gradient field';

    /**
     * @example
     * default: {
     *   colors: [
     *     {
     *       color: {
     *         r: 0,
     *         g: 0,
     *         b: 0,
     *         a: 1
     *       }
     *     },
     *     {
     *       color: {
     *         r: 255,
     *         g: 255,
     *         b: 255,
     *         a: 1
     *       }
     *     }
     *   ]
     * }
     */
    this.default = data.default || {};

    /**
     * @readonly
     * @private
     */
    this.type = 'gradient';

    /**
     * Manually defined names get priority. If no name is set, try to set it to the lower
     * snake case of the label provided. If no label is set, fall back to hardcoded value.
     */
    this.name = data.name || Util.toSnakeCase(this.label) || 'gradient_field';
  }
}
