import Util from '../../utils.js';
import Field from '../field.js';

export default class Spacing extends Field {
  /**
   * This field provides a user interface (UI) for content creators to set padding and
   * margin. Spacing fields have a .css property that returns CSS based on the field's
   * value. Learn more about the generated CSS property. Spacing fields are supported in
   * modules. Spacing fields can only be used as style fields.
   * @see {@link https://developers.hubspot.com/en/docs/cms/building-blocks/module-theme-fields#spacing}
   * @see {@link https://developers.hubspot.com/docs/cms/building-blocks/module-theme-fields-overview#generated-css}
   * @param {object} data The JSON data used to generate the field.
   * @param {object} [data.default={}] object containing a padding object and margin object.
   * Margin at this time only supports "top" and "bottom" adjustments.
   * @param {object} [data.default.padding] // @todo
   * @param {object} [data.default.padding.top] // @todo
   * @param {number} [data.default.padding.top.value] // @todo
   * @param {string} [data.default.padding.top.units] // @todo
   * @param {object} [data.default.padding.bottom] // @todo
   * @param {number} [data.default.padding.bottom.value] // @todo
   * @param {string} [data.default.padding.bottom.units] // @todo
   * @param {object} [data.default.padding.left] // @todo
   * @param {number} [data.default.padding.left.value] // @todo
   * @param {string} [data.default.padding.left.units] // @todo
   * @param {object} [data.default.padding.right] // @todo
   * @param {number} [data.default.padding.right.value] // @todo
   * @param {string} [data.default.padding.right.units] // @todo
   * @param {object} [data.default.margin] // @todo
   * @param {object} [data.default.margin.top] // @todo
   * @param {number} [data.default.margin.top.value] // @todo
   * @param {string} [data.default.margin.top.units] // @todo
   * @param {object} [data.default.margin.bottom] // @todo
   * @param {number} [data.default.margin.bottom.value] // @todo
   * @param {string} [data.default.margin.bottom.units] // @todo
   * @param {object} [data.default.margin.left] // @todo
   * @param {number} [data.default.margin.left.value] // @todo
   * @param {string} [data.default.margin.left.units] // @todo
   * @param {object} [data.default.margin.right] // @todo
   * @param {number} [data.default.margin.right.value] // @todo
   * @param {string} [data.default.margin.right.units] // @todo
   * -------------------------------------------------------------------------------------
   * @param {string} [data.help_text] Text that will appear in the editor via tooltip to
   * assist the content creator. Best used for information that is supplementary but not
   * required to use the field.
   * @param {string} [data.id] Unique id for a field. This is generated by HubSpot. When
   * building locally you do not need to specify this id.
   * @param {string} [data.inline_help_text] Help text that will be shown inline below the
   * label of the field (limit 300 chars). Best used for information required to use the
   * field.
   * @param {string} [data.label='Spacing field'] The text the content creator sees
   * describing the field. May contain spaces.
   * @param {boolean} [data.locked=false] Determines if the field is editable in the content
   * editor. If true, the field will not appear in the content editor.
   * @param {string} [data.name='spacing_field'] The variable name you will use to refer
   * to this field's values, and is what the value of the field is stored against. Cannot
   * contain spaces or special characters. If no name is provided, it will default to a lower 
   * snake case value of the label.
   * @param {boolean} [data.required=false] Determines if the field can be left blank in the
   * editor. If true, content will not be allowed to publish without filling out this field.
   * @param {Array} [data.visibility] Determines the display conditions for a field.
   * @param {'half_width'|null} [data.display_width=null] Allows for side by side module
   * fields in content editors, rather than full-width fields, when set to "half_width". The
   * field will appear side-by-side with the next field in the fields.json file, as long as
   * that field is also set to "half_width".
   */
  constructor (data = {}) {
    super(data);
    this.label = data.label || 'Spacing field';

    /**
     * @example
     * default: {
     *   padding: {
     *     top: {
     *       value: 10,
     *       units: 'px'
     *     },
     *     bottom: {
     *       value: 10,
     *       units: 'px'
     *     },
     *     left: {
     *       value: 10,
     *       units: 'px'
     *     },
     *     right: {
     *       value: 10,
     *       units: 'px'
     *     }
     *   },
     *   margin: {
     *     top: {
     *       value: 10,
     *       units: 'px'
     *     },
     *     bottom: {
     *       value: 10,
     *       units: 'px'
     *     }
     *   }
     * }
     */
    this.default = data.default || {};

    /**
     * @readonly
     * @private
     */
    this.type = 'spacing';

    /**
     * Manually defined names get priority. If no name is set, try to set it to the lower
     * snake case of the label provided. If no label is set, fall back to hardcoded value.
     */
    this.name = data.name || Util.toSnakeCase(this.label) || 'spacing_field';
  }
}
