import Util from '../../utils.js';
import Field from '../field.js';

export default class Image extends Field {
  /**
   * Image fields provide an easy interface for content creators to add images to a module
   * or theme. Image fields provide a file picker interface that lists images from the File
   * Manager. Since images can be used and displayed in different ways, developers can limit
   * the sizing options available to the content creator in the UI as well as allow for
   * lazy-loading of images. Image fields are supported in modules. Images can be used as
   * style fields. You should only use Image fields as style fields, if the image will be
   * purely presentational, not convey meaning and not a background image. This is to follow
   * best practices for accessibility.
   * @see {@link https://developers.hubspot.com/en/docs/cms/building-blocks/module-theme-fields#image}
   * @param {object} data The JSON data used to generate the field.
   * @param {object} [data.default={}] Image object. // @todo
   * @param {boolean} [data.responsive=true] Determines if the image is to act responsively
   * or have a fixed height and width.
   * @param {boolean} [data.resizable=true] // @todo
   * @param {boolean} [data.show_loading=false] Determines if the controls for choosing to
   * lazy load the image are shown in the page editor.
   * {@link https://developers.hubspot.com/docs/cms/guides/speed/lazy-loading}
   * -------------------------------------------------------------------------------------
   * @param {string} [data.help_text] Text that will appear in the editor via tooltip to
   * assist the content creator. Best used for information that is supplementary but not
   * required to use the field.
   * @param {string} [data.id] Unique id for a field. This is generated by HubSpot. When
   * building locally you do not need to specify this id.
   * @param {string} [data.inline_help_text] Help text that will be shown inline below the
   * label of the field (limit 300 chars). Best used for information required to use the field.
   * @param {string} [data.label='Image field'] The text the content creator sees describing the
   * field. May contain spaces.
   * @param {boolean} [data.locked=false] Determines if the field is editable in the content
   * editor. If true, the field will not appear in the content editor.
   * @param {string} [data.name='image_field'] The variable name you will use to refer to this
   * field's values, and is what the value of the field is stored against. Cannot contain
   * spaces or special characters. If no name is provided, it will default to a lower 
   * snake case value of the label.
   * @param {boolean} [data.required=false] Determines if the field can be left blank in the
   * editor. If true, content will not be allowed to publish without filling out this field.
   * @param {Array} [data.visibility] Determines the display conditions for a field.
   * @param {'half_width'|null} [data.display_width=null] Allows for side by side module
   * fields in content editors, rather than full-width fields, when set to "half_width". The
   * field will appear side-by-side with the next field in the fields.json file, as long as
   * that field is also set to "half_width".
   */
  constructor (data = {}) {
    super(data);
    this.label = data.label || 'Image field';
    this.responsive = data.responsive ?? true;
    this.resizable = data.resizable ?? true;
    this.show_loading = !!data.show_loading;
    this.default = data.default || {
      size_type: 'auto',
      src: '',
      alt: null,
      loading: 'lazy'
    };
    
    /**
     * @readonly
     * @private
     */
    this.type = 'icon';

    /**
     * Manually defined names get priority. If no name is set, try to set it to the lower
     * snake case of the label provided. If no label is set, fall back to hardcoded value.
     */
    this.name = data.name || Util.toSnakeCase(this.label) || 'image_field';
  }
}
