import Util from '../../utils.js';
import Field from '../field.js';

export default class Number extends Field {
  /**
   * Number fields provide an easy interface for content creators to enter in or adjust
   * numerical values and options. This can be used for creating percentage based items or
   * anything where numbers are needed for input. Number fields are supported in modules.
   * Number fields can be used as style fields.
   * @see {@link https://developers.hubspot.com/en/docs/cms/building-blocks/module-theme-fields#number}
   * @param {object} data The JSON data used to generate the field.
   * @param {number|null} [data.default=null] A default number to be used.
   * @param {'slider'|undefined} [data.display] If set to "slider", displays a number
   * slider below the input.
   * @param {number} [data.min] The maximum value of the input.
   * @param {number} [data.max] The minimum value of the input.
   * @param {string} [data.prefix] Added as a prefix to the number field. Note: Using the
   * suffix and prefix parameters has no effect on the numerical value of the field.
   * They are simply for display purposes in the content editor.
   * @param {suffix} [data.suffix] Added as a suffix to the number field. Note: Using the
   * suffix and prefix parameters has no effect on the numerical value of the field.
   * They are simply for display purposes in the content editor.
   * @param {number} [data.step=1] The step attribute specifies the size of each movement
   * (an increment or jump between values). The step attribute is used to limit down the
   * amount of allowed values. // @todo Make sure this works with number input (i.e. can't enter values manually outside of step)
   * -------------------------------------------------------------------------------------
   * @param {string} [data.help_text] Text that will appear in the editor via tooltip to
   * assist the content creator. Best used for information that is supplementary but not
   * required to use the field.
   * @param {string} [data.id] Unique id for a field. This is generated by HubSpot. When
   * building locally you do not need to specify this id.
   * @param {string} [data.inline_help_text] Help text that will be shown inline below the
   * label of the field (limit 300 chars). Best used for information required to use the field.
   * @param {string} [data.label='Number field'] The text the content creator sees describing the
   * field. May contain spaces.
   * @param {boolean} [data.locked=false] Determines if the field is editable in the content
   * editor. If true, the field will not appear in the content editor.
   * @param {string} [data.name='number_field'] The variable name you will use to refer to this
   * field's values, and is what the value of the field is stored against. Cannot contain
   * spaces or special characters. If no name is provided, it will default to a lower 
   * snake case value of the label.
   * @param {boolean} [data.required=false] Determines if the field can be left blank in the
   * editor. If true, content will not be allowed to publish without filling out this field.
   * @param {Array} [data.visibility] Determines the display conditions for a field.
   * @param {'half_width'|null} [data.display_width=null] Allows for side by side module
   * fields in content editors, rather than full-width fields, when set to "half_width". The
   * field will appear side-by-side with the next field in the fields.json file, as long as
   * that field is also set to "half_width".
   */
  constructor (data = {}) {
    super(data);
    this.label = data.label || 'Number field';
    this.step = data.step ?? 1;

    /**
     * @readonly
     * @private
     */
    this.type = 'number';

    /**
     * Manually defined names get priority. If no name is set, try to set it to the lower
     * snake case of the label provided. If no label is set, fall back to hardcoded value.
     */
    this.name = data.name || Util.toSnakeCase(this.label) || 'number_field';
  }
}
