import Util from '../../utils.js';
import Field from '../field.js';

export default class Text extends Field {
  /**
   * Text fields provide content creators a simple text editing experience with no rich
   * text functionality. Text fields initially show as a single line, but can actually
   * expand to be textareas, supporting multiple lines. Use these when you do not want
   * content creators to have control over formatting. If you do want to provide
   * formatting controls use rich text fields. Text fields are supported in modules.
   * @see {@link https://developers.hubspot.com/en/docs/cms/building-blocks/module-theme-fields#text}
   * @param {object} data The JSON data used to generate the field.
   * @param {string} [data.default] Text string.
   * @param {boolean} [data.allow_new_line=false] // @todo
   * @param {boolean} [data.show_emoji_picker=false] // @todo
   * @param {string} [data.validation_regex=''] // @todo
   * -------------------------------------------------------------------------------------
   * @param {string} [data.help_text] Text that will appear in the editor via tooltip to
   * assist the content creator. Best used for information that is supplementary but not
   * required to use the field.
   * @param {string} [data.id] Unique id for a field. This is generated by HubSpot. When
   * building locally you do not need to specify this id.
   * @param {string} [data.inline_help_text] Help text that will be shown inline below the
   * label of the field (limit 300 chars). Best used for information required to use the field.
   * @param {string} [data.label='Text field'] The text the content creator sees describing the
   * field. May contain spaces.
   * @param {boolean} [data.locked=false] Determines if the field is editable in the content
   * editor. If true, the field will not appear in the content editor.
   * @param {string} [data.name='text_field'] The variable name you will use to refer to this
   * field's values, and is what the value of the field is stored against. Cannot contain
   * spaces or special characters. If no name is provided, it will default to a lower 
   * snake case value of the label.
   * @param {boolean} [data.required=false] Determines if the field can be left blank in the
   * editor. If true, content will not be allowed to publish without filling out this field.
   * @param {Array} [data.visibility] Determines the display conditions for a field.
   * @param {'half_width'|null} [data.display_width=null] Allows for side by side module
   * fields in content editors, rather than full-width fields, when set to "half_width". The
   * field will appear side-by-side with the next field in the fields.json file, as long as
   * that field is also set to "half_width".
   */
  constructor (data = {}) {
    super(data);
    this.label = data.label || 'Text field';
    this.validation_regex = data.validation_regex || '';
    this.allow_new_line = !!data.allow_new_line;
    this.show_emoji_picker = !!data.show_emoji_picker;

    /**
     * @readonly
     * @private
     */
    this.type = 'text';

    /**
     * Manually defined names get priority. If no name is set, try to set it to the lower
     * snake case of the label provided. If no label is set, fall back to hardcoded value.
     */
    this.name = data.name || Util.toSnakeCase(this.label) || 'text_field';

    this.path = this.name;
    this.children?.forEach(child => {
      child.path = this.name + '.' + child.path;
    });
  }
}
