import Util from '../../utils.js';
import Field from '../field.js';

export default class Video extends Field {
  /**
   * Video fields provide content editors with a place to add HubSpot Video to their
   * module content without the need of using rich text fields.
   * @see {@link https://developers.hubspot.com/en/docs/cms/building-blocks/module-theme-fields#video}
   * @param {object} data The JSON data used to generate the field.
   * @param {object} [data.default] Video object with settings for "player_id", "height",
   * "width", "size_type", "conversion_asset", "loop_video", "mute_by_default", "autoplay",
   *  and "hide_control". // @todo Document subproperties
   * @param {object} [data.default.conversion_asset] // @todo
   * @param {('FORM'|'CTA'|'')} [data.default.conversion_asset.type=''] Accepts either
   * 'FORM', 'CTA', or ''.
   * @param {string} [data.default.conversion_asset.id=''] The id of the Form or CTA type.
   * @param {('PRE'|'POST')} [data.default.conversion_asset.position=''] Whether the
   * conversion asset should be shown before the video starts or after it ends. Accepts
   * either "PRE" or "POST".
   * @param {boolean} [data.resizable=true] // @todo
   * @param {boolean} [data.show_advanced_options=false] Whether content creators can see
   * advanced default options.
   * @param {boolean} [data.show_preview=true] // @todo
   * -------------------------------------------------------------------------------------
   * @param {string} [data.help_text] Text that will appear in the editor via tooltip to
   * assist the content creator. Best used for information that is supplementary but not
   * required to use the field.
   * @param {string} [data.id] Unique id for a field. This is generated by HubSpot. When
   * building locally you do not need to specify this id.
   * @param {string} [data.inline_help_text] Help text that will be shown inline below the
   * label of the field (limit 300 chars). Best used for information required to use the field.
   * @param {string} [data.label='Videoplayer field'] The text the content creator sees describing the
   * field. May contain spaces.
   * @param {boolean} [data.locked=false] Determines if the field is editable in the content
   * editor. If true, the field will not appear in the content editor.
   * @param {string} [data.name='videoplayer_field'] The variable name you will use to refer to this
   * field's values, and is what the value of the field is stored against. Cannot contain
   * spaces or special characters. If no name is provided, it will default to a lower 
   * snake case value of the label.
   * @param {boolean} [data.required=false] Determines if the field can be left blank in the
   * editor. If true, content will not be allowed to publish without filling out this field.
   * @param {Array} [data.visibility] Determines the display conditions for a field.
   * @param {'half_width'|null} [data.display_width=null] Allows for side by side module
   * fields in content editors, rather than full-width fields, when set to "half_width". The
   * field will appear side-by-side with the next field in the fields.json file, as long as
   * that field is also set to "half_width".
   */
  constructor (data = {}) {
    super(data);
    this.label = data.label || 'Videoplayer field';
    this.resizable = data.resizable ?? true;
    this.show_preview = data.show_preview ?? true;
    this.show_advanced_options = !!data.show_advanced_options;

    /**
     * Case-insensitize some property values.
     */
    this.supported_types = data.supported_types?.map(type => type.toUpperCase?.()) || [
      'EXTERNAL', 'CONTENT', 'FILE', 'EMAIL_ADDRESS', 'BLOG'
    ];
    if (this.default?.conversion_asset?.type) {
      this.default.conversion_asset.type = this.default.conversion_asset.type.toUpperCase?.(); 
    }
    if (this.default?.conversion_asset?.position) {
      this.default.conversion_asset.position = this.default.conversion_asset.position.toUpperCase?.(); 
    }

    /**
     * @readonly
     * @private
     */
    this.type = 'videoplayer';

    /**
     * Manually defined names get priority. If no name is set, try to set it to the lower
     * snake case of the label provided. If no label is set, fall back to hardcoded value.
     */
    this.name = data.name || Util.toSnakeCase(this.label) || 'videoplayer_field';
  }
}
